import { theme } from './theme';

const palette = {
  ...theme.colors,
  cyan400: theme.colors.accent,
  cyan500: theme.colors.tertiary,
  cyan600: '#00b36d',
  green400: theme.colors.tertiary,
  green500: theme.colors.tertiary,
  red400: theme.colors.error,
  red500: theme.colors.error,
  yellow400: '#FACC15',
  yellow500: '#EAB308',
  white: '#FFFFFF',
  black: theme.colors.black,
  gray400: theme.colors.onSurfaceVariant,
  gray500: theme.colors.outline,
  gray600: theme.colors.onPrimaryContainer,
  gray800: theme.colors.surfaceContainerLow,
  gray900: theme.colors.surfaceContainerLowest,
};

export default {
  light: {
    text: palette.onSurface,
    textSecondary: palette.onSurfaceVariant,
    background: palette.background,
    backgroundSecondary: palette.surfaceContainerLow,
    card: palette.surfaceContainer,
    border: palette.outlineVariant,
    tint: palette.tertiary,
    accent: palette.accent,
    success: palette.tertiary,
    error: palette.error,
    warning: palette.yellow400,
    tabIconDefault: palette.onSurfaceVariant,
    tabIconSelected: palette.tertiary,
  },
  dark: {
    text: palette.onSurface,
    textSecondary: palette.onSurfaceVariant,
    background: palette.background,
    backgroundSecondary: palette.surfaceContainerLow,
    card: palette.surfaceContainer,
    border: palette.outlineVariant,
    tint: palette.tertiary,
    accent: palette.accent,
    success: palette.tertiary,
    error: palette.error,
    warning: palette.yellow400,
    tabIconDefault: palette.onSurfaceVariant,
    tabIconSelected: palette.tertiary,
  },
  palette,
  theme,
};
